sudo: required
dist: xenial

language: python
cache: pip
before_install:
  - sudo apt-get install -y libopenmpi-dev
script:
  - pytest yairl/
matrix:
  include:
  - name: "Linting"
    python: "3.7"
    before_install: []
    install:
      - pip install flake8 isort
    script:
      - ci/code_checks.sh
    after_success: []

  - name: "3.5 Unit Tests"
    python: "3.5"
  - name: "3.6 Unit Tests"
    python: "3.6"
  - name: "3.7 Unit Tests"
    python: "3.7"
  - name: "3.7 Coverage Tests"
    python: "3.7"
    install:
      - pip install codecov
      - pip install -r requirements.txt
    script:
      - pytest --cov=yairl/ yairl/