sudo: required
dist: xenial

branches:
  only:
    - master

language: python
cache: pip
before_install:
  - sudo apt-get install -y libopenmpi-dev
install:
  - pip install '.[test,cpu]'
script:
  - pytest -vv tests/

matrix:
  include:
  - name: "Linting"
    python: "3.7"
    install:
      - pip install '.[dev,cpu]'
    script:
      - ci/lint.sh

  - name: "3.7 Coverage Tests"
    python: "3.7"
    install:
      # Install in developer mode so codecov can match paths
      - pip install -e '.[test,cpu]'
    script:
      - py.test -vv --cov-report=xml --cov=. tests/
    after_success:
      - codecov

  - name: "3.7 Static Type Checking"
    python: "3.7"
    install:
      - pip install '.[test,cpu]'
      - pip install pytype
    script:
      - ci/type_check.sh

  - name: "3.6 Unit Tests"
    python: "3.6"
  - name: "3.7 Unit Tests"
    python: "3.7"
